"-": &dockerbuild
  steps:
    - checkout

    # Which version of ruby?
    - run:
        name: Which ruby?
        command: ruby --version | tee ruby-version-for-ci.txt

    # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

    # Restore bundle cache
    - restore_cache:
        keys:
          - bundler-packages-v2-{{ checksum "ruby-version-for-ci.txt" }}-{{ checksum "rufo.gemspec" }}-{{ checksum "bin/verify-sample-code" }}

    - run:
        name: Bundle Install
        command: bundle check || bundle install

    - run:
        name: Run rspec
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress
    - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -f 'coverage/coverage.xml'
    - run:
        name: Run RuboCop
        command: |
          bundle exec rake rubocop
    - run:
        name: Run Rufo
        command: |
          bundle exec rake rufo:run

    - run:
        name: Verify rufo works against sample codebases
        command: |
          bin/verify-sample-code

    # Store bundle cache
    - save_cache:
        key: bundler-packages-v2-{{ checksum "ruby-version-for-ci.txt" }}-{{ checksum "rufo.gemspec" }}-{{ checksum "bin/verify-sample-code" }}
        paths:
          - vendor/bundle
          - Gemfile.lock

    # Save test results for timing analysis
    - store_test_results:
        path: test_results

version: 2
jobs:
  build-3-0-1:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:3.0.1
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: /home/circleci/project/vendor/bundle
  build-2-7-3:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:2.7.3
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: /home/circleci/project/vendor/bundle
  build-2-6-7:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:2.6.7
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: /home/circleci/project/vendor/bundle
  build-2-6-1:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle

workflows:
  version: 2
  test:
    jobs:
      - build-3-0-1
      - build-2-7-3
      - build-2-6-7
      - build-2-6-1
